version: '3'

services:
  pzem2mqtt01_reset:
    container_name: pzem2mqtt01_reset
    build: .
    restart: always
    # volumes:
    #   - ./config:/app/config
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/ttyUSB0
    networks:
      - back_network

networks:
  back_network:
    external: true
